// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Accione
{
    public string CodAccion { get; set; }

    public string Seccion { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Perfile> Perfils { get; set; } = new List<Perfile>();
}