// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CaracterPermisosAdjunto
{
    public int Id { get; set; }

    public string NumPermiso { get; set; }

    public byte[] AdjuntoXml { get; set; }

    public byte[] AdjuntoPdf { get; set; }
}