// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CClaveInstalacion
{
    public int Id { get; set; }

    public string ClaveInstalacion { get; set; }

    public string Descripcion { get; set; }
}