// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CClaveSubproducto
{
    public int Id { get; set; }

    public string ClaveSubProducto { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<DocumentoProducto> DocumentoProductos { get; set; } = new List<DocumentoProducto>();
}