// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CertificadosProveedore
{
    public string EmpresaId { get; set; }

    public string NumeroFolioCertificado { get; set; }

    public string RfcCertificado { get; set; }

    public DateOnly FechaEmisionCertificado { get; set; }

    public string ResultadoCertificado { get; set; }

    public bool Activo { get; set; }

    public byte[] AdjuntoPdfcertificado { get; set; }

    public byte[] AdjuntoXmlcertificado { get; set; }

    public virtual Empresa Empresa { get; set; }
}