// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CEstadoTanque
{
    public string EstadoTanque { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Tanque> Tanques { get; set; } = new List<Tanque>();
}