// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CompAlmTransporteDiario
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public int? Periodo { get; set; }

    public string PermisoTransporte { get; set; }

    public string ClaveVehiculo { get; set; }

    public decimal? TarifaDeTransporte { get; set; }

    public decimal? CargoPorCapacidadTrans { get; set; }

    public decimal? CargoPorUsoTrans { get; set; }

    public decimal? CargoVolumetricoTrans { get; set; }
}