// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CompAlmProveedorNacionalMensual
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public string ProveedorId { get; set; }

    public string PermisoProveedor { get; set; }

    public string RfcClienteOproveedor { get; set; }

    public string NombreClienteOproveedor { get; set; }

    public virtual Documento Documento { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }
}