// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CompAlmCertificado
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public string NumeroFolioCertificado { get; set; }

    public string RfcCertificado { get; set; }

    public DateOnly? FechaEmisionCertificado { get; set; }

    public string ResultadoCertificado { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }
}