// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CompAlmCfdinacionalDocumento
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public int Consecutivo { get; set; }

    public byte[] Xml { get; set; }

    public byte[] Pdf { get; set; }

    public string ClaveTanque { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }
}