// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CompAlmCfdinacional
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public int Consecutivo { get; set; }

    public string Uuid { get; set; }

    public string TipoCfdi { get; set; }

    public decimal? PrecioCompra { get; set; }

    public decimal? Contraprestacion { get; set; }

    public decimal? TarifaDeAlmacenamiento { get; set; }

    public decimal? CargoPorCapacidadAlmac { get; set; }

    public decimal? CargoPorUsoAlmac { get; set; }

    public decimal? CargoVolumetricoAlmac { get; set; }

    public decimal? Descuento { get; set; }

    public DateTime? FechaYhoraTransaccion { get; set; }

    public decimal? ValorNumerico { get; set; }

    public int? Um { get; set; }

    public string TipoEs { get; set; }

    public string TipoDocumento { get; set; }

    public string Aclaracion { get; set; }

    public string ClaveTanque { get; set; }

    public int? ConsecutivoRecepcion { get; set; }

    public string ProveedorId { get; set; }

    public string PermisoProveedor { get; set; }

    public string RfcClienteOproveedor { get; set; }

    public string NombreClienteOproveedor { get; set; }

    public decimal? PoderCalorifico { get; set; }

    public decimal? PrecioUnitario { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }

    public virtual TClaveUnidadMedidum UmNavigation { get; set; }
}