// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class ControlExistenciasAcumOpsRecepcionDiario
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string Producto { get; set; }

    public DateTime? FechaActual { get; set; }

    public DateTime? FechaDiaAnterior { get; set; }

    public decimal? ValorNumerico { get; set; }

    public string Um { get; set; }

    public TimeOnly? HoraRecepcionAcumulado { get; set; }
}