// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class ControlExistenciasMensual
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string Producto { get; set; }

    public DateTime? FechaActual { get; set; }

    public DateTime? FechaYhoraEstaMedicionMes { get; set; }

    public decimal? ValorNumerico { get; set; }
}