// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CTipoEvento
{
    public long? Id { get; set; }

    public string TipoEvento { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Bitacora> Bitacoras { get; set; } = new List<Bitacora>();

    public virtual ICollection<DocumentoBitacora> DocumentoBitacoras { get; set; } = new List<DocumentoBitacora>();
}