// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class CTipoImpExp
{
    public string TipoDocumento { get; set; }

    public string TipoImportacion { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<EmpresaImpExp> EmpresaImpExps { get; set; } = new List<EmpresaImpExp>();

    public virtual TipoDocumento TipoDocumentoNavigation { get; set; }
}