// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DictamenDiario
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NumeroFolioDictamen { get; set; }

    public string RfcDictamen { get; set; }

    public string LoteDictamen { get; set; }

    public DateOnly? FechaEmisionDictamen { get; set; }

    public string ResultadoDictamen { get; set; }
}