// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Dictamene
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NumeroFolioDictamen { get; set; }

    public string RfcDictamen { get; set; }

    public string RfcRepresentanteLegalProveedor { get; set; }

    public string RfcPersonal { get; set; }

    public string LoteDictamen { get; set; }

    public int IdClaveProducto { get; set; }

    public DateOnly FechaEmisionDictamen { get; set; }

    public string ResultadoDictamen { get; set; }

    public bool Activo { get; set; }

    public byte[] AdjuntoPdfdictamen { get; set; }

    public byte[] AdjuntoXmldcitamen { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual CClaveProducto IdClaveProductoNavigation { get; set; }

    public virtual Plantum Planta { get; set; }
}