// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Diesel
{
    public string ProductoId { get; set; }

    public decimal? ComposDeCombustibleNoFosilEnDiesel { get; set; }

    public string DieselConCombustibleNoFosil { get; set; }
}