// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DispensariosManguera
{
    public string PlantaId { get; set; }

    public string ClaveDispensario { get; set; }

    public int Consecutivo { get; set; }

    public string IdentificadorManguera { get; set; }

    public virtual Plantum Planta { get; set; }
}