// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DocumentoDiarioDispenEntrega
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public string ClaveIdentificacionTanque { get; set; }

    public string ClaveIdentificadorDispensario { get; set; }

    public string IdentificadorManguera { get; set; }

    public int Consecutivo { get; set; }

    public string TipoDeRegistro { get; set; }

    public decimal? VolEntregadoTotalAcumValorNumerico { get; set; }

    public decimal? VolEntregadoTotalInstaValorNumerico { get; set; }

    public decimal? PrecioVentaTotalizadorInsta { get; set; }

    public DateTime? FechaYhoraEntrega { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }
}