// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DocumentoTanqueExistencium
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public string ClaveIdentificacionTanque { get; set; }

    public decimal? VolumenExistenciasAnterior { get; set; }

    public decimal? VolumenAcumOpsRecepcion { get; set; }

    public decimal? VolumenvolumenAcumOpsEntrega { get; set; }

    public decimal? VolumenExistencias { get; set; }

    public TimeOnly? HoraRecepcionAcumulado { get; set; }

    public TimeOnly? HoraEntregaAcumulado { get; set; }

    public DateTime? FechayHoraEstaMedicion { get; set; }

    public DateTime? FechayHoraMedicionAnterior { get; set; }

    public string Um { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }
}