// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DocumentoBitacora
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public int NumeroRegistro { get; set; }

    public DateTime? FechaYhoraEvento { get; set; }

    public string UsuarioResponsable { get; set; }

    public string TipoEvento { get; set; }

    public string DescripcionEvento { get; set; }

    public string IdentificacionEvento { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }

    public virtual CTipoEvento TipoEventoNavigation { get; set; }
}