// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DocumentoDiarioMedicionDucto
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public int Consecutivo { get; set; }

    public string ClaveDucto { get; set; }

    public string SistemaMedicionDispensario { get; set; }

    public string LocalizOdescripSistMedicionDispensario { get; set; }

    public DateOnly? VigenciaCalibracionSistMedicionDispensario { get; set; }

    public decimal? IncertidumbreMedicionSistMedicionDispensario { get; set; }
}