// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DocumentoMedicionTanque
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public string ClaveIdentificacionTanque { get; set; }

    public long Consecutivo { get; set; }

    public string SistemaMedicionTanque { get; set; }

    public string LocalizOdescripSistMedicionTanque { get; set; }

    public DateOnly? VigenciaCalibracionSistMedicionTanque { get; set; }

    public decimal? IncertidumbreMedicionSistMedicionTanque { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }
}