// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DocumentoGasNatural
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public decimal? FraccionMolar { get; set; }

    public string ComplementoGnc { get; set; }

    public decimal? PoderCalorifico { get; set; }
}