// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DocumentoProducto
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public string ProductoId { get; set; }

    public int? ClaveProducto { get; set; }

    public int? ClaveSubProducto { get; set; }

    public string MarcaComercial { get; set; }

    public string Marcaje { get; set; }

    public string ConcentracionSustanciaMarcaje { get; set; }

    public int? Um { get; set; }

    public virtual CClaveProducto ClaveProductoNavigation { get; set; }

    public virtual CClaveSubproducto ClaveSubProductoNavigation { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual TClaveUnidadMedidum UmNavigation { get; set; }
}