// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DocumentoDiarioDispenEntrega1
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public int Periodo { get; set; }

    public int Consecutivo { get; set; }

    public string IdentificadorManguera { get; set; }

    public int? TotalEntregas { get; set; }

    public decimal? SumaVolEntregadoValorNumerico { get; set; }

    public string SumaVolEntregadoUm { get; set; }

    public int? TotalDocumentos { get; set; }

    public decimal? SumaVentas { get; set; }
}