// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DocumentoAutomaticoMensual
{
    public string EmpresaId { get; set; }

    public string NoDocumento { get; set; }

    public string PlantaId { get; set; }

    public DateOnly FechaPeticion { get; set; }

    public int Mes { get; set; }

    public int Anio { get; set; }

    public decimal? VolExistenciaMes { get; set; }

    public decimal? ImporteTotalRecep { get; set; }

    public decimal? TotalEntrega { get; set; }

    public string Estatus { get; set; }
}