// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DocumentoGenerado
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public long Consecutivo { get; set; }

    public string Guid { get; set; }

    public DateTime FechaGeneracion { get; set; }

    public byte[] Xml { get; set; }

    public string Descripcion { get; set; }

    public string Nombre { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }
}