// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Documento
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public int? Periodo { get; set; }

    public string TipoDocumento { get; set; }

    public string VersionCtrVol { get; set; }

    public string RfcProveedorInformatico { get; set; }

    public int? TipoCaracter { get; set; }

    public int? ModalidadPermiso { get; set; }

    public string NumPermiso { get; set; }

    public string NumContratoOasignacion { get; set; }

    public string InstalacionAlmacenGasNatural { get; set; }

    public string ClaveInstalacion { get; set; }

    public string DescripcionInstalacion { get; set; }

    public int? NumeroPozos { get; set; }

    public int? NumeroTanques { get; set; }

    public int? NumeroDuctosEntradaSalida { get; set; }

    public int? NumeroDuctosTransporteDistribucion { get; set; }

    public int? NumeroDispensarios { get; set; }

    public DateTime? FechayHoraReporteMes { get; set; }

    public DateTime? FechayHoraCorteDiario { get; set; }

    public DateTime? FechaGeneracion { get; set; }

    public string IdentificadorUnico { get; set; }

    public string Estatus { get; set; }

    public string PorcentajeCaptura { get; set; }

    public string NombreImportacion { get; set; }

    public virtual CompAlmProveedorNacionalMensual CompAlmProveedorNacionalMensual { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual DocumentoEstatus EstatusNavigation { get; set; }

    public virtual TClavePermiso ModalidadPermisoNavigation { get; set; }

    public virtual Plantum Planta { get; set; }

    public virtual CCaracter TipoCaracterNavigation { get; set; }

    public virtual TipoDocumento TipoDocumentoNavigation { get; set; }

    public virtual VersionControlVolumetrico VersionCtrVolNavigation { get; set; }
}