// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class DocumentoProveedore
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public int? Periodo { get; set; }

    public int? Consecutivo { get; set; }

    public string RfcProveedor { get; set; }

    public string CodigoP { get; set; }
}