// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Ducto
{
    public string PlantaId { get; set; }

    public string ClaveIdentificacionDucto { get; set; }

    public string LocalizacionYodescripcionDucto { get; set; }

    public decimal DiametroDucto { get; set; }

    public decimal CapacidadGasTalon { get; set; }

    public int Um { get; set; }
}