// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class EmpresaImpExp
{
    public string EmpresaId { get; set; }

    public string Tipo { get; set; }

    public string TipoDocumento { get; set; }

    public string TipoLayout { get; set; }

    public string Ruta { get; set; }

    public bool Activo { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual CTipoImpExp TipoDocumentoNavigation { get; set; }

    public virtual CTipo TipoNavigation { get; set; }
}