// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class EmpresaProducto
{
    public string PlantaId { get; set; }

    public string ProductoId { get; set; }

    public bool Disponibilidad { get; set; }

    public virtual Plantum Planta { get; set; }

    public virtual Producto Producto { get; set; }
}