// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Empresa
{
    public string EmpresaId { get; set; }

    public string RazonSocial { get; set; }

    public string Rfc { get; set; }

    public string RfcRepresentanteLegal { get; set; }

    public DateTime FechaCreacion { get; set; }

    public string VersionCtrVol { get; set; }

    public bool Activa { get; set; }

    public virtual ICollection<Bitacora> Bitacoras { get; set; } = new List<Bitacora>();

    public virtual ICollection<CertificadosProveedore> CertificadosProveedores { get; set; } = new List<CertificadosProveedore>();

    public virtual ICollection<CompAlmCertificado> CompAlmCertificados { get; set; } = new List<CompAlmCertificado>();

    public virtual ICollection<CompAlmCfdinacionalDocumento> CompAlmCfdinacionalDocumentos { get; set; } = new List<CompAlmCfdinacionalDocumento>();

    public virtual ICollection<CompAlmCfdinacional> CompAlmCfdinacionals { get; set; } = new List<CompAlmCfdinacional>();

    public virtual ICollection<CompAlmDictaman> CompAlmDictamen { get; set; } = new List<CompAlmDictaman>();

    public virtual ICollection<CompAlmProveedorNacionalMensual> CompAlmProveedorNacionalMensuals { get; set; } = new List<CompAlmProveedorNacionalMensual>();

    public virtual ICollection<Dictamene> Dictamenes { get; set; } = new List<Dictamene>();

    public virtual ICollection<DocumentoBitacora> DocumentoBitacoras { get; set; } = new List<DocumentoBitacora>();

    public virtual ICollection<DocumentoDiarioDispenEntrega> DocumentoDiarioDispenEntregas { get; set; } = new List<DocumentoDiarioDispenEntrega>();

    public virtual ICollection<DocumentoDiarioManguera> DocumentoDiarioMangueras { get; set; } = new List<DocumentoDiarioManguera>();

    public virtual ICollection<DocumentoDiarioMedicionDispensario> DocumentoDiarioMedicionDispensarios { get; set; } = new List<DocumentoDiarioMedicionDispensario>();

    public virtual ICollection<DocumentoDispensario> DocumentoDispensarios { get; set; } = new List<DocumentoDispensario>();

    public virtual ICollection<DocumentoExistencium> DocumentoExistencia { get; set; } = new List<DocumentoExistencium>();

    public virtual ICollection<DocumentoGasLp> DocumentoGasLps { get; set; } = new List<DocumentoGasLp>();

    public virtual ICollection<DocumentoGenerado> DocumentoGenerados { get; set; } = new List<DocumentoGenerado>();

    public virtual ICollection<DocumentoMedicionTanque> DocumentoMedicionTanques { get; set; } = new List<DocumentoMedicionTanque>();

    public virtual ICollection<DocumentoProducto> DocumentoProductos { get; set; } = new List<DocumentoProducto>();

    public virtual ICollection<DocumentoTanqueExistencium> DocumentoTanqueExistencia { get; set; } = new List<DocumentoTanqueExistencium>();

    public virtual ICollection<DocumentoTanque> DocumentoTanques { get; set; } = new List<DocumentoTanque>();

    public virtual ICollection<Documento> Documentos { get; set; } = new List<Documento>();

    public virtual ICollection<EmpresaImpExp> EmpresaImpExps { get; set; } = new List<EmpresaImpExp>();

    public virtual ICollection<EmpresaPlantum> EmpresaPlanta { get; set; } = new List<EmpresaPlantum>();

    public virtual ICollection<EmpresaProveedor> EmpresaProveedors { get; set; } = new List<EmpresaProveedor>();

    public virtual ICollection<EntregaDiario> EntregaDiarios { get; set; } = new List<EntregaDiario>();

    public virtual ICollection<EntregasMensuale> EntregasMensuales { get; set; } = new List<EntregasMensuale>();

    public virtual ICollection<PerfilEmpresa> PerfilEmpresas { get; set; } = new List<PerfilEmpresa>();

    public virtual ICollection<RecepcionDiario> RecepcionDiarios { get; set; } = new List<RecepcionDiario>();

    public virtual ICollection<RecepcionesMensuale> RecepcionesMensuales { get; set; } = new List<RecepcionesMensuale>();

    public virtual VersionControlVolumetrico VersionCtrVolNavigation { get; set; }
}