// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class EmpresaCfgNotificacione
{
    public string EmpresaId { get; set; }

    public string TipoNotificacion { get; set; }
}