// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class EmpresaProveedor
{
    public string EmpresaId { get; set; }

    public string ProveedorId { get; set; }

    public bool Disponibilidad { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Proveedore Proveedor { get; set; }
}