// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class EntregasMensuale
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public int TotalEntregasMes { get; set; }

    public decimal SumaVolEntregadoMesValorNumerico { get; set; }

    public int SumaVolEntregadoMesUm { get; set; }

    public int TotalDocumentosMes { get; set; }

    public decimal ImporteTotalEntregasMensual { get; set; }

    public decimal? PoderCalorifico { get; set; }

    public int? PoderCalorificoUm { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }

    public virtual TClaveUnidadMedidum SumaVolEntregadoMesUmNavigation { get; set; }
}