// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class GasLp
{
    public string ProductoId { get; set; }

    public decimal? ComposDePropanoEnGasLp { get; set; }

    public decimal? ComposDeButanoEnGasLp { get; set; }

    public virtual Producto Producto { get; set; }
}