// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Gasolina
{
    public string ProductoId { get; set; }

    public decimal? ComposOctanajeGasolina { get; set; }

    public decimal? ComposDeCombustibleNoFosilEnGasolina { get; set; }

    public string GasolinaConCombustibleNoFosil { get; set; }
}