// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class HistoryPass
{
    public string UsuarioId { get; set; }

    public long Consecutivo { get; set; }

    public string HashPassword { get; set; }

    public DateTime Fecha { get; set; }

    public virtual Usuario Usuario { get; set; }
}