// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class LogMovimiento
{
    public long Id { get; set; }

    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public string Usuario { get; set; }

    public DateTime? Fecha { get; set; }

    public string Descripcion { get; set; }

    public string Tipo { get; set; }

    public string Ip { get; set; }

    public string Mac { get; set; }
}