// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Manuale
{
    public int Consecutivo { get; set; }

    public string NombreManual { get; set; }

    public byte[] AdjuntoPdf { get; set; }
}