// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class MedicionDucto
{
    public string PlantaId { get; set; }

    public string ClaveIdentificacionDucto { get; set; }

    public long Consecutivo { get; set; }

    public string SistemaMedicionDucto { get; set; }

    public string LocalizOdescripSistMedicionDucto { get; set; }

    public DateOnly VigenciaCalibracionSistMedicionDucto { get; set; }

    public decimal IncertidumbreMedicionSistMedicionDucto { get; set; }
}