// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class MedicionDispensario
{
    public string PlantaId { get; set; }

    public string ClaveDispensario { get; set; }

    public int Consecutivo { get; set; }

    public string SistemaMedicionDispensario { get; set; }

    public string LocalizOdescripSistMedicionDispensario { get; set; }

    public DateOnly VigenciaCalibracionSistMedicionDispensario { get; set; }

    public decimal IncertidumbreMedicionSistMedicionDispensario { get; set; }

    public virtual Plantum Planta { get; set; }
}