// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Perfile
{
    public long PerfilId { get; set; }

    public string Perfil { get; set; }

    public string Descripcion { get; set; }

    public string Acciones { get; set; }

    public virtual ICollection<PerfilEmpresa> PerfilEmpresas { get; set; } = new List<PerfilEmpresa>();

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();

    public virtual ICollection<Accione> CodAccions { get; set; } = new List<Accione>();
}