// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class PerfilAccion
{
    public long PerfilId { get; set; }

    public string CodAccion { get; set; }

    public string Id { get; set; }

    public virtual Accione CodAccionNavigation { get; set; }

    public virtual Perfile Perfil { get; set; }
}