// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class PeticionPassword
{
    public long Id { get; set; }

    public string Guid { get; set; }

    public string Correo { get; set; }

    public DateTime FechaPeticion { get; set; }

    public bool Usado { get; set; }
}