// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Plantum
{
    public string PlantaId { get; set; }

    public string DescripcionPlanta { get; set; }

    public int? IdTipoCaracter { get; set; }

    public int? IdModalidadPermiso { get; set; }

    public string NumPermiso { get; set; }

    public string NumContratoOasignacion { get; set; }

    public string InstalacionAlmacenGasNatural { get; set; }

    public string ClaveInstalacion { get; set; }

    public string DescripcionInstalacion { get; set; }

    public int? NumeroPozos { get; set; }

    public int? NumeroTanques { get; set; }

    public int? NumeroDuctosEntradaSalida { get; set; }

    public int? NumeroDuctosTransporteDistribucion { get; set; }

    public int? NumeroDispensarios { get; set; }

    public bool? Activa { get; set; }

    public virtual ICollection<Bitacora> Bitacoras { get; set; } = new List<Bitacora>();

    public virtual ICollection<CompAlmCertificado> CompAlmCertificados { get; set; } = new List<CompAlmCertificado>();

    public virtual ICollection<CompAlmCfdinacionalDocumento> CompAlmCfdinacionalDocumentos { get; set; } = new List<CompAlmCfdinacionalDocumento>();

    public virtual ICollection<CompAlmCfdinacional> CompAlmCfdinacionals { get; set; } = new List<CompAlmCfdinacional>();

    public virtual ICollection<CompAlmDictaman> CompAlmDictamen { get; set; } = new List<CompAlmDictaman>();

    public virtual ICollection<CompAlmProveedorNacionalMensual> CompAlmProveedorNacionalMensuals { get; set; } = new List<CompAlmProveedorNacionalMensual>();

    public virtual ICollection<Dictamene> Dictamenes { get; set; } = new List<Dictamene>();

    public virtual ICollection<Dispensario> Dispensarios { get; set; } = new List<Dispensario>();

    public virtual ICollection<DispensariosManguera> DispensariosMangueras { get; set; } = new List<DispensariosManguera>();

    public virtual ICollection<DocumentoBitacora> DocumentoBitacoras { get; set; } = new List<DocumentoBitacora>();

    public virtual ICollection<DocumentoDiarioDispenEntrega> DocumentoDiarioDispenEntregas { get; set; } = new List<DocumentoDiarioDispenEntrega>();

    public virtual ICollection<DocumentoDiarioManguera> DocumentoDiarioMangueras { get; set; } = new List<DocumentoDiarioManguera>();

    public virtual ICollection<DocumentoDiarioMedicionDispensario> DocumentoDiarioMedicionDispensarios { get; set; } = new List<DocumentoDiarioMedicionDispensario>();

    public virtual ICollection<DocumentoDispensario> DocumentoDispensarios { get; set; } = new List<DocumentoDispensario>();

    public virtual ICollection<DocumentoExistencium> DocumentoExistencia { get; set; } = new List<DocumentoExistencium>();

    public virtual ICollection<DocumentoGasLp> DocumentoGasLps { get; set; } = new List<DocumentoGasLp>();

    public virtual ICollection<DocumentoGenerado> DocumentoGenerados { get; set; } = new List<DocumentoGenerado>();

    public virtual ICollection<DocumentoMedicionTanque> DocumentoMedicionTanques { get; set; } = new List<DocumentoMedicionTanque>();

    public virtual ICollection<DocumentoProducto> DocumentoProductos { get; set; } = new List<DocumentoProducto>();

    public virtual ICollection<DocumentoTanqueExistencium> DocumentoTanqueExistencia { get; set; } = new List<DocumentoTanqueExistencium>();

    public virtual ICollection<DocumentoTanque> DocumentoTanques { get; set; } = new List<DocumentoTanque>();

    public virtual ICollection<Documento> Documentos { get; set; } = new List<Documento>();

    public virtual ICollection<EmpresaPlantum> EmpresaPlanta { get; set; } = new List<EmpresaPlantum>();

    public virtual ICollection<EmpresaProducto> EmpresaProductos { get; set; } = new List<EmpresaProducto>();

    public virtual ICollection<EntregaDiario> EntregaDiarios { get; set; } = new List<EntregaDiario>();

    public virtual ICollection<EntregasMensuale> EntregasMensuales { get; set; } = new List<EntregasMensuale>();

    public virtual TClavePermiso IdModalidadPermisoNavigation { get; set; }

    public virtual CCaracter IdTipoCaracterNavigation { get; set; }

    public virtual ICollection<MedicionDispensario> MedicionDispensarios { get; set; } = new List<MedicionDispensario>();

    public virtual ICollection<MedicionTanque> MedicionTanques { get; set; } = new List<MedicionTanque>();

    public virtual ICollection<PerfilEmpresa> PerfilEmpresas { get; set; } = new List<PerfilEmpresa>();

    public virtual ICollection<PlantaProducto> PlantaProductos { get; set; } = new List<PlantaProducto>();

    public virtual ICollection<RecepcionDiario> RecepcionDiarios { get; set; } = new List<RecepcionDiario>();

    public virtual ICollection<RecepcionesMensuale> RecepcionesMensuales { get; set; } = new List<RecepcionesMensuale>();

    public virtual ICollection<Tanque> Tanques { get; set; } = new List<Tanque>();
}