// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class PlantaGeolocalizacion
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public int? Consecutivo { get; set; }

    public decimal? GeolocalizacionLatitud { get; set; }

    public decimal? GeolocalizacionLongitud { get; set; }
}