// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Producto
{
    public string ProductoId { get; set; }

    public int IdClaveProducto { get; set; }

    public int? IdClaveSubProducto { get; set; }

    public string Descripcion { get; set; }

    public string MarcaComercial { get; set; }

    public string Marcaje { get; set; }

    public string ConcentracionSustanciaMarcaje { get; set; }

    public int IdUm { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<DocumentoProducto> DocumentoProductos { get; set; } = new List<DocumentoProducto>();

    public virtual ICollection<EmpresaProducto> EmpresaProductos { get; set; } = new List<EmpresaProducto>();

    public virtual GasLp GasLp { get; set; }

    public virtual ICollection<PlantaProducto> PlantaProductos { get; set; } = new List<PlantaProducto>();
}