// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Proveedore
{
    public string NoProveedor { get; set; }

    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string RfcP { get; set; }

    public string RazonSocialP { get; set; }

    public string CodigoP { get; set; }

    public string NumPermiso { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<EmpresaProveedor> EmpresaProveedors { get; set; } = new List<EmpresaProveedor>();
}