// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class RecepcionesDiario
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string Producto { get; set; }

    public string ClaveIdentificacionTanque { get; set; }

    public int? TotalRecepciones { get; set; }

    public decimal? SumaVolRecepValorNumerico { get; set; }

    public string SumaVolRecepUm { get; set; }

    public int? TotalDocumentos { get; set; }

    public decimal? SumaCompras { get; set; }
}