// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class RecepcionDiario
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public string ClaveIdentificacionTanque { get; set; }

    public int NumerDeRegistro { get; set; }

    public decimal? VolInicialTanqueValorNumerico { get; set; }

    public decimal? VolFinalTanqueValorNumerico { get; set; }

    public decimal? VolRecepValorNumerico { get; set; }

    public decimal? Temperatura { get; set; }

    public decimal? PresionAbsoluta { get; set; }

    public DateTime? FechaYhoraInicioRecepcion { get; set; }

    public DateTime? FechaYhoraFinalRecepcion { get; set; }

    public bool? IsDucto { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }
}