// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class RecepcionesMensuale
{
    public string EmpresaId { get; set; }

    public string PlantaId { get; set; }

    public string NoDocumento { get; set; }

    public int TotalRecepcionesMes { get; set; }

    public decimal SumaVolRecepMesValorNumerico { get; set; }

    public int SumaVolRecepMesUm { get; set; }

    public int TotalDocumentosMes { get; set; }

    public decimal ImporteTotalRecepcionesMensual { get; set; }

    public decimal? PoderCalorifico { get; set; }

    public int? PoderCalorificoUm { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual Plantum Planta { get; set; }

    public virtual TClaveUnidadMedidum SumaVolRecepMesUmNavigation { get; set; }
}