// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class Tanque
{
    public string PlantaId { get; set; }

    public string ClaveIdentificacionTanque { get; set; }

    public string LocalizacionYodescripcionTanque { get; set; }

    public DateTime VigenciaCalibracionTanque { get; set; }

    public decimal CapTotalValorNumerico { get; set; }

    public decimal CapOperativaValorNumerico { get; set; }

    public decimal CapUtilValorNumerico { get; set; }

    public decimal? CapFondajeValorNumerico { get; set; }

    public decimal? CapGasTalonValorNumerico { get; set; }

    public decimal VolMinOperaValorNumrico { get; set; }

    public string EstadoTanque { get; set; }

    public int Um { get; set; }

    public virtual CEstadoTanque EstadoTanqueNavigation { get; set; }

    public virtual ICollection<MedicionTanque> MedicionTanques { get; set; } = new List<MedicionTanque>();

    public virtual Plantum Planta { get; set; }

    public virtual TClaveUnidadMedidum UmNavigation { get; set; }
}