// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class TClaveUnidadMedidum
{
    public int Id { get; set; }

    public string ClaveUnidadMedida { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<CompAlmCfdinacional> CompAlmCfdinacionals { get; set; } = new List<CompAlmCfdinacional>();

    public virtual ICollection<DocumentoProducto> DocumentoProductos { get; set; } = new List<DocumentoProducto>();

    public virtual ICollection<DocumentoTanque> DocumentoTanques { get; set; } = new List<DocumentoTanque>();

    public virtual ICollection<EntregasMensuale> EntregasMensuales { get; set; } = new List<EntregasMensuale>();

    public virtual ICollection<RecepcionesMensuale> RecepcionesMensuales { get; set; } = new List<RecepcionesMensuale>();

    public virtual ICollection<Tanque> Tanques { get; set; } = new List<Tanque>();
}