// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class TClavePermiso
{
    public int Id { get; set; }

    public string ModalidadPermiso { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Documento> Documentos { get; set; } = new List<Documento>();

    public virtual ICollection<Plantum> Planta { get; set; } = new List<Plantum>();
}