// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class TipoProveedor
{
    public int? TipoProveedor1 { get; set; }

    public string CodigoP { get; set; }

    public string Descripcion { get; set; }
}