// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class TipoDocumento
{
    public string TipoDocumento1 { get; set; }

    public string Descripcion { get; set; }

    public virtual CTipoImpExp CTipoImpExp { get; set; }

    public virtual ICollection<Documento> Documentos { get; set; } = new List<Documento>();
}