// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.ateb.Entities;

public partial class VersionControlVolumetrico
{
    public string VersionCtrVol { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Documento> Documentos { get; set; } = new List<Documento>();

    public virtual ICollection<Empresa> Empresas { get; set; } = new List<Empresa>();
}